version: "2"
services:
  node:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 5017:3500
    command: "node index.js"
